# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CalendarDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Masonry', '~> 1.0.1'
pod 'YYModel', '~> 1.0.4'

  target 'CalendarDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalendarDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
